#################################################################################################
# Copyright (C) 2026 Intel Corporation, All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#################################################################################################

from .schemas import BENCHMARK_ERROR_RE, CSV_FIELDS, SCHEMA_VERSION, SEARCH_RUNTIME_SCHEMA, infer_scheduler_metadata
from .utils import ensure_dir, now_iso, read_json, resolve_executable, shell_init_with_env, shell_join, write_json
from .catalog import (
    DEFAULT_KERNEL_CATALOG_PATH,
    BENCHMARK_STREAMK_TILE_SHAPES,
    EXPANDED_GEMM_TILE_SHAPES,
    EXPANDED_STREAMK_TILE_SHAPES,
    SEED_KERNELS,
    STREAMK_TILE_SHAPES,
    build_kernel_catalog,
    generated_expanded_streamk_kernel_catalog,
    generated_generator_kernel_catalog,
    generated_layered_bmg_kernel_catalog,
    generated_layered_bmg_scheduler_expanded_kernel_catalog,
    generated_level0_kernel_catalog,
    ilp_class,
    kernel_catalog_entry,
    load_persisted_kernel_catalog,
)
from .source_templates import is_valid_xe2_tile_sg, observed_bmg_template_space
from .prefilter import (
    compute_ilp,
    prefilter_candidates,
    priority_score,
    sort_candidates_by_priority,
)
from .constraints import (
    DEFAULT_BUILD_CONFIG_PATH,
    DEFAULT_RUNTIME_CONFIG_PATH,
    apply_probe_results_to_profiles,
    apply_run_probe_constraints,
    apply_static_probe_constraints,
    blocked,
    blocked_rule_for_row,
    default_compiler_profiles,
    default_constraints,
    load_persisted_build_config,
    load_persisted_runtime_config,
    selected_compile_env,
    selected_runtime_env,
)
from .hw_specs import (
    DEFAULT_HW_REFERENCE_SPECS_PATH,
    compute_efficiency_bounds,
    detect_probe_anomalies,
    load_hw_reference_specs,
    resolve_hw_reference_spec,
)
from .device_target import (
    discover_xpu_smi_devices,
    parse_xpu_smi_discovery,
    parse_xpu_smi_json,
    resolve_device_target,
    resolve_profiles_device_target,
    selected_device_id,
    target_from_device_info,
)
from .candidates import (
    build_candidate_build_manifest,
    build_compiler_profile_probe_entries,
    build_dpas_probe_entry,
    build_phase_a_probe_entries,
    build_screening_entries,
    candidate_class,
    candidate_id_for,
    choose_candidates_for_shape,
    default_shapes,
    dry_run_shapes,
    generate_candidate_space,
    generate_confirmation_entries,
    select_compiler_profile_id,
    select_probe_shape,
    write_config,
)
from .runner import (
    collect_environment_metadata,
    parse_benchmark_log,
    parse_metric,
    parse_streamk_example_log,
    run_benchmark,
    run_entries_with_benchmark,
    run_entries_with_streamk_example,
    timeout_rows,
)
from .selector import (
    build_dispatch_table,
    build_candidate_coverage_report,
    build_phase_a_summary,
    build_phase_b_summary,
    build_reference_comparison,
    build_run_summary,
    median_or_nan,
    write_results_csv,
)
from .dispatch import (
    DISPATCH_KEY_FIELDS,
    build_dispatch_index,
    dispatch_shape_key_tuple,
    load_dispatch_table,
    lookup_dispatch_entry,
    normalize_dispatch_shape_key,
    validate_dispatch_table,
)
from .ali_dataset import build_ali_gemm_docs
from .analysis import REGULAR_GEMM_FULL_CONFIG_FIELDS, SCHEDULER_BRUTEFORCE_CONFIG_FIELDS, build_regular_gemm_gap_scan, build_scheduler_bruteforce_gap_scan, build_scheduler_bruteforce_plan, collect_regular_gemm_full_config_rows, collect_scheduler_bruteforce_full_config_rows
from .phase_a import build_compiler_flags_probe_summary, empty_anomaly_report, run_phase_a_probe
from .cli import build_parser, dispatch_lookup_from_args, main
from .bundle import build_artifact_bundle_manifest, export_product_bundle_manifest, validate_product_bundle_manifest
from .build_plan import benchmark_batch_plan_by_kernel_id, benchmark_command_strings, benchmark_exe_for_build_plan, benchmark_log_paths, build_candidate_build_plan, detect_available_vcpus, execute_candidate_build_plan, execute_candidate_build_preflight_plans, resolve_candidate_build_jobs, run_entries_with_batch_benchmarks, validate_candidate_auto_build_mode
from .workflow import SEARCH_STRATEGY_PRESETS, apply_bruteforce_scheduler_search_defaults, apply_search_strategy_defaults, limit_shapes_and_reference, load_target_shapes_and_reference, workflow

__all__ = [
    "BENCHMARK_ERROR_RE",
    "BENCHMARK_STREAMK_TILE_SHAPES",
    "CSV_FIELDS",
    "DEFAULT_KERNEL_CATALOG_PATH",
    "EXPANDED_GEMM_TILE_SHAPES",
    "EXPANDED_STREAMK_TILE_SHAPES",
    "DEFAULT_BUILD_CONFIG_PATH",
    "DEFAULT_RUNTIME_CONFIG_PATH",
    "DEFAULT_HW_REFERENCE_SPECS_PATH",
    "DISPATCH_KEY_FIELDS",
    "SCHEMA_VERSION",
    "SEARCH_STRATEGY_PRESETS",
    "SEARCH_RUNTIME_SCHEMA",
    "SEED_KERNELS",
    "STREAMK_TILE_SHAPES",
    "SCHEDULER_BRUTEFORCE_CONFIG_FIELDS",
    "REGULAR_GEMM_FULL_CONFIG_FIELDS",
    "apply_probe_results_to_profiles",
    "apply_run_probe_constraints",
    "apply_static_probe_constraints",
    "apply_bruteforce_scheduler_search_defaults",
    "apply_search_strategy_defaults",
    "blocked",
    "blocked_rule_for_row",
    "build_candidate_build_manifest",
    "build_candidate_build_plan",
    "build_candidate_coverage_report",
    "build_regular_gemm_gap_scan",
    "build_scheduler_bruteforce_gap_scan",
    "benchmark_batch_plan_by_kernel_id",
    "benchmark_command_strings",
    "benchmark_exe_for_build_plan",
    "benchmark_log_paths",
    "build_compiler_profile_probe_entries",
    "build_compiler_flags_probe_summary",
    "compute_efficiency_bounds",
    "detect_probe_anomalies",
    "discover_xpu_smi_devices",
    "detect_available_vcpus",
    "dispatch_lookup_from_args",
    "build_dispatch_table",
    "build_dispatch_index",
    "build_dpas_probe_entry",
    "build_kernel_catalog",
    "build_parser",
    "build_phase_a_probe_entries",
    "build_phase_a_summary",
    "build_phase_b_summary",
    "build_reference_comparison",
    "build_run_summary",
    "build_scheduler_bruteforce_plan",
    "build_ali_gemm_docs",
    "build_artifact_bundle_manifest",
    "build_screening_entries",
    "candidate_class",
    "candidate_id_for",
    "choose_candidates_for_shape",
    "collect_environment_metadata",
    "collect_regular_gemm_full_config_rows",
    "collect_scheduler_bruteforce_full_config_rows",
    "default_compiler_profiles",
    "default_constraints",
    "default_shapes",
    "dry_run_shapes",
    "empty_anomaly_report",
    "execute_candidate_build_plan",
    "execute_candidate_build_preflight_plans",
    "export_product_bundle_manifest",
    "ensure_dir",
    "infer_scheduler_metadata",
    "generate_candidate_space",
    "generated_generator_kernel_catalog",
    "generated_expanded_streamk_kernel_catalog",
    "generated_layered_bmg_kernel_catalog",
    "generated_layered_bmg_scheduler_expanded_kernel_catalog",
    "generate_confirmation_entries",
    "generated_level0_kernel_catalog",
    "ilp_class",
    "kernel_catalog_entry",
    "is_valid_xe2_tile_sg",
    "load_dispatch_table",
    "load_persisted_kernel_catalog",
    "observed_bmg_template_space",
    "limit_shapes_and_reference",
    "load_target_shapes_and_reference",
    "load_hw_reference_specs",
    "load_persisted_build_config",
    "load_persisted_runtime_config",
    "lookup_dispatch_entry",
    "main",
    "median_or_nan",
    "now_iso",
    "normalize_dispatch_shape_key",
    "parse_benchmark_log",
    "parse_metric",
    "parse_streamk_example_log",
    "read_json",
    "resolve_executable",
    "resolve_hw_reference_spec",
    "resolve_device_target",
    "resolve_candidate_build_jobs",
    "resolve_profiles_device_target",
    "selected_runtime_env",
    "selected_device_id",
    "selected_compile_env",
    "run_benchmark",
    "run_entries_with_benchmark",
    "run_entries_with_batch_benchmarks",
    "run_entries_with_streamk_example",
    "run_phase_a_probe",
    "select_compiler_profile_id",
    "select_probe_shape",
    "shell_init_with_env",
    "shell_join",
    "parse_xpu_smi_discovery",
    "parse_xpu_smi_json",
    "target_from_device_info",
    "timeout_rows",
    "validate_candidate_auto_build_mode",
    "validate_product_bundle_manifest",
    "validate_dispatch_table",
    "workflow",
    "write_config",
    "write_json",
    "write_results_csv",
]
