#!/usr/bin/env python3
"""Generate per-batch benchmarks_sycl.hpp."""
import re, argparse, shutil
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
FULL = REPO / "benchmarks/gemm/benchmarks_sycl.hpp"
CACHE = REPO / "benchmarks/gemm/benchmarks_sycl.hpp.cache"
STREAMK_TILE_DEF_RE = re.compile(r"BMG_STREAMK_TILE\((\d+),\s*(\d+),\s*(\d+)\)")

# Tile sizes generated by BMG_DECLARE_EXPANDED_GEMM_TILES
EXPANDED_TILES_SG8x4 = {
    (64,64,32),(64,64,64),(64,128,32),(64,128,64),(64,256,32),(64,256,64),
    (128,64,32),(128,64,64),(128,128,32),(128,128,64),(128,256,32),(128,256,64),(128,256,16),(128,512,32),
    (256,64,32),(256,64,64),(256,128,32),(256,128,64),(256,192,64),(256,256,32),(256,256,64),(256,256,16),
    (512,64,32),(512,64,64),(512,128,32),(512,128,64),(512,256,32),(512,256,64),
}

def load_streamk_tiles(*filenames):
    tiles = set()
    for filename in filenames:
        path = REPO / "benchmarks/gemm" / filename
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        tiles.update(tuple(map(int, match)) for match in STREAMK_TILE_DEF_RE.findall(text))
    return tiles

# Must match ALL StreamK/DP/SplitK tiles already instantiated in full HPP.
EXPANDED_STREAMK_TILES = load_streamk_tiles(
    "bmg_streamk_seed_tile.def",
    "bmg_streamk_expanded_tile.def",
    "bmg_streamk_exhaustive_missing_tile.def",
)

def full_text():
    # Always re-read from canonical source to avoid stale cache
    if CACHE.exists():
        CACHE.unlink()
    shutil.copy2(FULL, CACHE)
    with open(CACHE) as f: return f.read()

def classify(name):
    m = re.match(r'^(\w+)_GemmExhaustive_(\d+)x(\d+)x(\d+)_SG(\d+)x(\d+)_ST(\d+)$', name)
    if m: return 'ge', m.group(1), {'M':m.group(2),'N':m.group(3),'K':m.group(4),'SGM':m.group(5),'SGN':m.group(6),'ST':m.group(7)}
    m = re.match(r'^(\w+)_(StreamK|DataParallel|SplitK)_(\d+)x(\d+)x(\d+)_SG(\d+)x(\d+)_ST(\d+)$', name)
    if m: return 'ske', m.group(1), {'MODE':m.group(2),'M':m.group(3),'N':m.group(4),'K':m.group(5),'SGM':m.group(6),'SGN':m.group(7),'ST':m.group(8)}
    m = re.match(r'^(\w+)_Gemm_(\d+)x(\d+)x(\d+)_SG(\d+)x(\d+)$', name)
    if m: return 'gs', m.group(1), {'M':m.group(2),'N':m.group(3),'K':m.group(4),'SGM':m.group(5),'SGN':m.group(6)}
    m = re.match(r'^(\w+)_(StreamK|DataParallel|SplitK)_(\d+)x(\d+)x(\d+)$', name)
    if m: return 'sk', m.group(1), {'M':m.group(3),'N':m.group(4),'K':m.group(5)}
    return 'hw', name, {}

def cfg_atom(pfx):
    if 'RRR' in pfx: return 'Gemm_Bench_BF16FP32_RRR', 'MMAAtom'
    if 'FP16FP16FP32' in pfx or pfx.startswith('BmgGemmFP16'): return 'Gemm_Bench_F16FP32_RCR', 'MMAAtomF16'
    if 'F16F16F16' in pfx: return 'Gemm_Bench_F16F16F16_RCR', 'MMAAtomF16AccF16'
    if 'TF32' in pfx: return 'Gemm_Bench_TF32FP32_RCR', 'MMAAtomTF32'
    return 'Gemm_Bench_BF16FP32_RCR', 'MMAAtom'

def streamk_cfg(pfx):
    if pfx == 'BmgGemmBF16BF16FP32_RRR':
        return 'Gemm_Bench_BF16BF16FP32_RRR_StreamK'
    if pfx == 'BmgGemmBF16BF16FP32_RCR':
        return 'Gemm_Bench_BF16BF16FP32_RCR_StreamK'
    if pfx == 'BmgGemmTF32TF32FP32_RCR':
        return 'Gemm_Bench_TF32TF32FP32_RCR_StreamK'
    if pfx == 'BmgGemmF16F16FP32_RCR':
        return 'Gemm_Bench_F16F16FP32_RCR_StreamK'
    if pfx == 'BmgGemmF16F16F16_RCR':
        return 'Gemm_Bench_F16F16F16_RCR_StreamK'
    raise ValueError(f'Unsupported StreamK prefix in mini HPP generation: {pfx}')

def streamk_exhaustive_cfg(pfx):
    if pfx == 'BmgGemmBF16BF16FP32_RRR':
        return 'Gemm_Bench_BF16BF16FP32_RRR_StreamKExhaustive'
    if pfx == 'BmgGemmBF16BF16FP32_RCR':
        return 'Gemm_Bench_BF16BF16FP32_RCR_StreamKExhaustive'
    raise ValueError(f'Unsupported exhaustive StreamK prefix in mini HPP generation: {pfx}')

def scheduler_enum(mode):
    if mode == 'StreamK':
        return 'GemmStreamK'
    if mode == 'DataParallel':
        return 'GemmDataParallel'
    return 'GemmSplitK'

def covered(name, text):
    """Check if kernel type is already defined in full HPP."""
    # Direct using declaration
    if re.search(rf'using\s+{re.escape(name)}\s*=', text): return True
    # CUTLASS_CREATE_GEMM_BENCHMARK already exists in full HPP
    if f'CUTLASS_CREATE_GEMM_BENCHMARK({name})' in text: return True
    t, pfx, p = classify(name)
    if t == 'gs' and p['SGM'] == '8' and p['SGN'] == '4':
        sz = (int(p['M']), int(p['N']), int(p['K']))
        if sz in EXPANDED_TILES_SG8x4: return True
    if t == 'sk':
        sz = (int(p['M']), int(p['N']), int(p['K']))
        if sz in EXPANDED_STREAMK_TILES: return True
    return False

def gen_mini(kernels, output):
    text = full_text()
    direct_kernels = set(re.findall(r'^\s*using\s+(\w+)\s*=', text, flags=re.M))
    emitted_streamk_tiles = set()

    declares = []
    registers = []
    for k in sorted(set(kernels)):
        t, pfx, p = classify(k)
        if t == 'hw':
            if k not in direct_kernels:
                raise ValueError(f"Unsupported non-pattern kernel in manifest: {k}")
            declares.append(f'CUTLASS_CREATE_GEMM_BENCHMARK({k});')
            continue
        c, a = cfg_atom(pfx)
        if t == 'ge':
            declares.append(f'BMG_DECLARE_EXHAUSTIVE_GEMM_TILE_STAGE({pfx}, {c}, {a}, {p["M"]}, {p["N"]}, {p["K"]}, {p["SGM"]}, {p["SGN"]}, {p["ST"]})')
        elif t == 'ske':
            declares.append(
                f'BMG_DECLARE_EXHAUSTIVE_STREAMK_TILE_STAGE({pfx}, {streamk_exhaustive_cfg(pfx)}, {p["MODE"]}, '
                f'{scheduler_enum(p["MODE"])}, {p["M"]}, {p["N"]}, {p["K"]}, {p["SGM"]}, {p["SGN"]}, {p["ST"]})'
            )
        elif t == 'gs':
            declares.append(f'BMG_DECLARE_GEMM_TILE_SG({pfx}, {c}, {a}, {p["M"]}, {p["N"]}, {p["K"]}, {p["SGM"]}, {p["SGN"]})')
        else:
            key = (pfx, p["M"], p["N"], p["K"])
            if key in emitted_streamk_tiles:
                continue
            emitted_streamk_tiles.add(key)
            declares.append(f'BMG_DECLARE_STREAMK_TILE({pfx}, {streamk_cfg(pfx)}, {p["M"]}, {p["N"]}, {p["K"]})')
    
    emitted_streamk_tiles.clear()
    for k in sorted(set(kernels)):
        t, pfx, p = classify(k)
        if t == 'hw':
            registers.append(f'  CUTLASS_BENCHMARK({k});')
        elif t == 'gs':
            registers.append(f'  BMG_REGISTER_GEMM_TILE_SG({pfx}, {p["M"]}, {p["N"]}, {p["K"]}, {p["SGM"]}, {p["SGN"]})')
        elif t == 'ge':
            registers.append(f'  BMG_REGISTER_EXHAUSTIVE_GEMM_TILE_STAGE({pfx}, {p["M"]}, {p["N"]}, {p["K"]}, {p["SGM"]}, {p["SGN"]}, {p["ST"]})')
        elif t == 'ske':
            registers.append(f'  BMG_REGISTER_EXHAUSTIVE_STREAMK_TILE_STAGE({pfx}, {p["MODE"]}, {p["M"]}, {p["N"]}, {p["K"]}, {p["SGM"]}, {p["SGN"]}, {p["ST"]})')
        elif t == 'sk':
            key = (pfx, p["M"], p["N"], p["K"])
            if key in emitted_streamk_tiles:
                continue
            emitted_streamk_tiles.add(key)
            registers.append(f'  BMG_REGISTER_STREAMK_TILE({pfx}, {p["M"]}, {p["N"]}, {p["K"]})')
    
    m = re.search(r'static void register_gemm_benchmarks', text)
    pos = m.start() if m else len(text)
    
    # Strip all BMG_DECLARE_*/BMG_REGISTER_*/BMG_SOURCE_* macro invocations
    # from the preamble — they generate types that conflict with batch declares.
    # Keep only #define macro definitions and template type definitions.
    lines = text[:pos].split('\n')
    preamble_lines = []
    in_macro_def = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('#define '):
            in_macro_def = stripped.endswith('\\')
            preamble_lines.append(line)
            continue
        if in_macro_def:
            preamble_lines.append(line)
            in_macro_def = stripped.endswith('\\')
            continue
        # Strip individual macro calls that generate kernel types
        # Match BMG_DECLARE_GEMM_TILE(, CUTLASS_CREATE_GEMM_BENCHMARK(, etc.
        if re.match(r'^(BMG_DECLARE_\w+|BMG_REGISTER_\w+|BMG_SOURCE_\w+|CUTLASS_CREATE_GEMM_BENCHMARK)\(', stripped):
            continue
        # Strip .def includes (macro generators)
        if stripped in {
            '#include "bmg_gemm_source_tile_sg.def"',
            '#include "bmg_streamk_seed_tile.def"',
            '#include "bmg_streamk_expanded_tile.def"',
            '#include "bmg_streamk_exhaustive_missing_tile.def"',
        }:
            continue
        preamble_lines.append(line)
    
    new_text = '\n'.join(preamble_lines)
    if declares:
        new_text += '\n// Batch kernel declarations\n' + '\n'.join(declares) + '\n'
    new_text += '\nstatic void register_gemm_benchmarks() {\n'
    new_text += '\n'.join(registers) + '\n}\n'
    
    with open(output, 'w') as f: f.write(new_text)
    print(f"Generated: {len(kernels)} k, {len(declares)} d, {len(registers)} r")

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--manifest", required=True); p.add_argument("--output", required=True)
    a = p.parse_args()
    with open(a.manifest) as f: k = [l.strip() for l in f if l.strip()]
    gen_mini(k, a.output)
